defaultEntryPoints = ["http", "https"]
[docker]
# endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
# watch = true
# exposedbydefault = false
# swarmmode = true
[web]
address = ":8080"
#  [web.auth.basic]
#  users = ["admin:$apr1$L1yDs/sN$7SZWo3MoaZbZy3IYVI/oD0"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
email = "contact@ngoclb.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

