entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /dynamic.yml
    watch: false

certificatesResolvers:
  http:
    acme:
      email: devbox@localhost.com
      storage: /acme.json
      httpChallenge:
        entryPoint: http

api:
  dashboard: true
  insecure: false
  debug: false

log:
  level: INFO

accessLog: true